/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package evaluacion;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Victor Rodriguez
 */
public class JPostre extends javax.swing.JFrame {

    /**
     * Creates new form JPostre
     */
    public JPostre() {
        initComponents();
    }
    Array objarray = new Array();
    Postre objp;
    ArrayList<String> otroingrediente1 = new ArrayList();
    ArrayList<String> otroingrediente2 = new ArrayList();
    ArrayList<String> otroingrediente3 = new ArrayList();

    public String getOtroingrediente1(int x) {
        return otroingrediente1.get(x);
    }

    public String getOtroingrediente2(int x) {
        return otroingrediente2.get(x);
    }

    public String getOtroingrediente3(int x) {
        return otroingrediente3.get(x);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtnom = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtingrediente = new javax.swing.JTextField();
        txtingrediente2 = new javax.swing.JTextField();
        txtingrediente3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnagregar = new javax.swing.JButton();
        btnbuscar = new javax.swing.JButton();
        btningredientes = new javax.swing.JButton();
        btnlista = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        txtdato = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btnmostrarnuevo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre: ");

        jLabel2.setText("Ingrediente 1:");

        jLabel3.setText("Ingrediente 2:");

        jLabel4.setText("Ingrediente 3:");

        btnagregar.setText("Agregar");
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });

        btnbuscar.setText("Buscar");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        btningredientes.setText("Nuevos Ingredientes");
        btningredientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btningredientesActionPerformed(evt);
            }
        });

        btnlista.setText("Postre dado de alta");
        btnlista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlistaActionPerformed(evt);
            }
        });

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        jLabel5.setText("Dato");

        btnmostrarnuevo.setText("Mostrar Postre con nuevo ingredientes");
        btnmostrarnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmostrarnuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtingrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtingrediente2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtingrediente3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnbuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnagregar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))
                        .addGap(33, 33, 33))))
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel5)
                .addGap(67, 67, 67)
                .addComponent(txtdato, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnmostrarnuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnlista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btningredientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtingrediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtingrediente2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtingrediente3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnagregar)
                        .addGap(9, 9, 9)
                        .addComponent(btnbuscar)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtdato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btningredientes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnmostrarnuevo)))
                .addGap(18, 18, 18)
                .addComponent(btnlista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        // TODO add your handling code here:
        String nombre = txtdato.getText();
        txtdato.getText();
        String datos = "";
        int pos = this.objarray.buscar(nombre);
        txtArea.setText("");
        txtdato.setText("");
        if (pos != -1) {
            int tam = objarray.size();
            for (int x = 0; x < tam; x++) {
                if (nombre.equals(this.objarray.valor(x).getNombre())) {
                    datos += "\nEl nombre es: " + objarray.valor(x).getNombre() + "\n";
                    datos += "El ingrediente uno es: " + objarray.valor(x).getI1() + "\n";
                    datos += "El ingrediente dos es: " + objarray.valor(x).getI2() + "\n";
                    datos += "El ingrediente tres es: " + objarray.valor(x).getI3() + "\n";

                }
            }
            txtArea.append("Los postres ingresados con el nombre: " + nombre + "son: " + datos);
        } else {
            JOptionPane.showMessageDialog(null, "El registro no existe");
        }
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
        // TODO add your handling code here:
        String nom = txtnom.getText();
        String i1 = txtingrediente.getText();
        String i2 = this.txtingrediente2.getText();
        String i3 = txtingrediente3.getText();
        this.objp = new Postre(nom, i1, i2, i3);
        this.objp.setNombre(nom);
        this.objp.setI1(i1);
        this.objp.setI2(i2);
        this.objp.setI3(i3);
        this.objarray.Agregar(objp);

        txtnom.setText("");
        txtingrediente.setText("");
        txtingrediente2.setText("");
        txtingrediente3.setText("");

    }//GEN-LAST:event_btnagregarActionPerformed

    private void btningredientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btningredientesActionPerformed
        // TODO add your handling code here:
        ////////////////ingrediente 1

        int res = 0, res1 = 0, res2 = 0;
        //JOptionPane.showMessageDialog(null, "Ingresar tres ingredientes mas.");
        String nom = this.txtdato.getText();
        int pos = this.objarray.buscar(nom);
        txtArea.setText("");
        txtdato.setText("");
        
        if (pos != -1) {

            for (int x = 0; x < objarray.size(); x++) {
                if (nom.equals(this.objarray.valor(x).getNombre())) {
                    String i1 = JOptionPane.showInputDialog(null, "Ingrese el ingrediente 1: ");
                    this.otroingrediente1.add(i1);

                        String i2 = JOptionPane.showInputDialog(null, "Ingrese el ingrediente 2: ");
                        this.otroingrediente2.add(i2);

                            String i3 = JOptionPane.showInputDialog(null, "Ingrese el ingrediente 3: ");
                            this.otroingrediente3.add(i3);
  
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Postre no existe");
        }


    }//GEN-LAST:event_btningredientesActionPerformed

    private void btnlistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlistaActionPerformed
        // TODO add your handling code here:
    String nombre = txtdato.getText();
        txtdato.getText();
        String datos = "";
        txtArea.setText("");
        txtdato.setText("");
            int tam = objarray.size();
            for (int x = 0; x < tam; x++) {
              if(nombre.equals(this.objarray.valor(x).getI1())||nombre.equals(objarray.valor(x).getI2())||nombre.equals(this.objarray.valor(x).getI3()) 
                      || nombre.equals(this.otroingrediente1.get(x)) || nombre.equals(this.otroingrediente2.get(x)) || nombre.equals(this.otroingrediente3.get(x)) ){
              datos += "El nombre del postre es: " + objarray.valor(x).getNombre() + "\n";     
            }else{
                  JOptionPane.showMessageDialog(null, "El registro no existe");
              }
            }
            txtArea.append("El ingrediente ingresado: " + nombre + " pertenece al postre: \n" + datos);
   
    }//GEN-LAST:event_btnlistaActionPerformed

    private void btnmostrarnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmostrarnuevoActionPerformed
        // TODO add your handling code here:
        String nombre = txtdato.getText();
        txtdato.getText();
        String datos = "";
        int pos = this.objarray.buscar(nombre);
        txtArea.setText("");
        txtdato.setText("");
        if (pos != -1) {
            int tam = objarray.size();
            for (int x = 0; x < tam; x++) {
                if (nombre.equals(this.objarray.valor(x).getNombre())) {
                    datos += "\nEl nombre es: " + objarray.valor(x).getNombre() + "\n";
                    datos += "El ingrediente uno es: " + objarray.valor(x).getI1() + "\n";
                    datos += "El ingrediente dos es: " + objarray.valor(x).getI2() + "\n";
                    datos += "El ingrediente tres es: " + objarray.valor(x).getI3() + "\n";
                    datos += "El ingrediente cuatro es: " + this.otroingrediente1.get(x) + "\n";
                    if (otroingrediente2.get(x) == null) {
                        datos += "El ingrediente cinco no tiene datos." + "\n";
                    }else{
                        datos += "El ingrediente cinco es: " + otroingrediente2.get(x) + "\n";
                    }
                    if (otroingrediente3.get(x) == null) {
                        datos += "El ingrediente seis no tiene datos." + "\n";
                    }else{
                        datos += "El ingrediente seis es: " + otroingrediente3.get(x) + "\n";
                    }

                }
            }
            txtArea.append("Los postres ingresados con el nombre: " + nombre + "son: " + datos);
        } else {
            JOptionPane.showMessageDialog(null, "El registro no existe");
        }
    }//GEN-LAST:event_btnmostrarnuevoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JPostre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JPostre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JPostre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JPostre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JPostre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btningredientes;
    private javax.swing.JButton btnlista;
    private javax.swing.JButton btnmostrarnuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextField txtdato;
    private javax.swing.JTextField txtingrediente;
    private javax.swing.JTextField txtingrediente2;
    private javax.swing.JTextField txtingrediente3;
    private javax.swing.JTextField txtnom;
    // End of variables declaration//GEN-END:variables
}
